### ISSUE TITLE
README content width should not expand on side drawer close

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/www#1]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.

## Description

> Description of the issue.

Encountered an error when closing the side menu (drawer). Upon closing, the README content width expands. This behavior differs from the previous behavior, where the README content simply shifted to the left.

## Related Issues

> Does this issue have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

#### Demo

> If relevant, provide a link to a live demo.

For a live demo of the issue, see

-   <https://stdlib.io/docs/api/v0.0.90/@stdlib/array>

#### Reproduction

> What steps are required to reproduce the unexpected output?

In order to reproduce this bug, do the following:

-   Navigate to the API docs.
-   Open a README.
-   Close the drawer.
-   The README content width expands.

#### Expected Results

> What are the expected results?

The following results are expected:

-   README content width does not expand.

#### Actual Results

> What are the actual results?

The following are the actual results:

-   README content width expands.

#### Environments

> What environments are affected (e.g., `Node v0.4.x`, `Chrome`, `IE 11`)? If Node.js, include the `npm` version, operating system, and any other potentially relevant platform information.

The following environments are affected:

-   Chrome

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by Planeshifter** [comment]
The behavior has been changed. Comments?

**Comment by kgryte** [comment]
I pulled down the latest and rebuilt the application. Locally, I am still seeing the same behavior, which does not match the behavior prior to the refactor preceding the webinar.

**Comment by kgryte** [comment]
This has now been resolved.
