### ISSUE TITLE
Top navigation styling issues

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/www#2]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.

## Description

> Description of the issue.

We need to fix the following styling issues with the API docs top navigation:

1.  navigation should not be sticky.
2.  item spacing/alignment should better match the main homepage
3.  s/Back to README/Documentation/

## Related Issues

> Does this issue have any related issues?

None.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

#### Demo

> If relevant, provide a link to a live demo.

For a live demo of the issue, see

-   <https://stdlib.io/docs/api/v0.0.90/@stdlib/array

#### Reproduction

> What steps are required to reproduce the unexpected output?

In order to reproduce this bug, do the following:

-   see the site.

#### Expected Results

> What are the expected results?

The following results are expected:

N/A

#### Actual Results

> What are the actual results?

The following are the actual results:

N/A

#### Environments

> What environments are affected (e.g., `Node v0.4.x`, `Chrome`, `IE 11`)? If Node.js, include the `npm` version, operating system, and any other potentially relevant platform information.

The following environments are affected:

-   Chrome

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by Planeshifter** [comment]
This issue has now been resolved.

**Comment by kgryte** [comment]
Feel free to close then.
