### ISSUE TITLE
API docs should include main website footer

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/www#3]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.

## Description

> Description of the issue.

The API docs should include the main website footer (or something similar). Currently, the footer lacks corresponding styling and is misaligned.

At some point, because we use GA, we need to link to our privacy policy, both in the API docs and on the main website.

## Related Issues

> Does this issue have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

#### Demo

> If relevant, provide a link to a live demo.

For a live demo of the issue, see

-   main website and API docs.

#### Reproduction

> What steps are required to reproduce the unexpected output?

In order to reproduce this bug, do the following:

-   see the website and API docs.

#### Expected Results

> What are the expected results?

The following results are expected:

N/A

#### Actual Results

> What are the actual results?

The following are the actual results:

N/A

#### Environments

> What environments are affected (e.g., `Node v0.4.x`, `Chrome`, `IE 11`)? If Node.js, include the `npm` version, operating system, and any other potentially relevant platform information.

The following environments are affected:

-   Chrome

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by Planeshifter** [comment]
The footer is now styled. Feedback is welcome.

**Comment by kgryte** [comment]
1.  We need to make the footer be center on the README content, not the page. Otherwise, when the drawer is shown, the footer content is page centered, which looks odd/unexpected when compared to the main content.
2.  Also, we need to move the footer to just below the fold (i.e., screen view) when main content is too short to fill an entire page. Otherwise, when the drawer is shown and the main content is insufficiently long, we show the footer above the fold, which is odd/unexpected when the side drawer extends to the bottom of the screen.

    This will likely mean that we may want specialized styling (CSS) for the footer when included in the API docs, as opposed to the main website and TypeScript docs.

**Comment by kgryte** [comment]
When the drawer is open, I find to be a bit odd/less than optimal that the footer can scroll above the bottom of the window and be adjacent to the bottom of the drawer. However, when the drawer is closed, it is fine.

For now, I think this is fine. We may want to revisit should we want the footer to include additional categories and navigation items. At which point, we'd want to opt for a full width footer residing below all content, including the side drawer. The side drawer would only scroll up on the page once we have reached the end of the main content. This would introduce a bit of complexity we can forgo for now.
