### ISSUE TITLE
[RFC]: add chat to the API documentation to facilitate user engagement

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/www#33]
### Description

This RFC proposes adding chat functionality to the API documentation to facilitate user engagement.

When a user has a question, particularly when navigating the project given its size, would be great to provide a mechanism by which a user can ask a question without needing to, e.g., navigate to GitHub and open an issue, but instead, ask in a (public) chat forum.

One potential solution is using Gitter [sidecar](https://sidecar.gitter.im/). We already use Gitter for community chat. This would simply embed the chat in the website, without a user needing to navigate to a separate website. 

### Related Issues

No.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
Given that we will want to embed the chat in a React app, will probably want to use custom buttons for toggling the chat. See the [Gitter example](https://gitlab.com/gitterHQ/sidecar/-/blob/3a3e1a544689ef6c73b9422ed8aa92a63182e6b1/examples/toggle-chat-class-buttons/index.html)).

**Comment by Planeshifter** [comment]
This has been added using `sidecar` with a custom toggle button.

**Comment by kgryte** [comment]
We probably don't want to show, or even allow, Gitter on mobile. Just not likely that someone is going to want to pull up Gitter chat while browsing around on their phone. In which case, keeping the bottom Gitter navigational element around for that use case makes sense to me, as we can potentially deep link it to open the Gitter app, if it is installed on a user's mobile device.

**Comment by Planeshifter** [comment]
Hmm, I didn't like to have two Gitter links in the footer because it forces one to navigate more elements when using the keyboard and is redundant (the sidecar button is a link that will also work when JS is disabled / can be right-clicked like any other `<a />` tag). We could use `@media` and depending on screen size either show the Gitter button or just a link in the bottom nav bar.

**Comment by kgryte** [comment]
Correct. I was not necessarily advocating for two links. But we could toggle the display based on the viewport.

**Comment by Planeshifter** [comment]
Yes, that would make sense to me! Same for the "Help" button too which may be in the way on mobile devices.

**Comment by Planeshifter** [comment]
Changed accordingly per https://github.com/stdlib-js/www/commit/ebdba3f0ea3b84e17955a7ee061343323da98611.

**Comment by kgryte** [comment]
Gitter chat has now been added and has been deployed. Closing...
