### ISSUE TITLE
[RFC]: investigate migrating from Material-UI v4 to Mui v5

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/www#38]
### Description

This RFC proposes investigating migration from Material-UI v4 to Mui v5. See [migration guide](https://mui.com/guides/migration-v4/).

Based on an initial skim, this should not be too difficult, as we mostly use fairly vanilla Material UI elements, such as buttons and icons. 

### Related Issues

No.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Planeshifter** [comment]
Pull request with migration has been filed.
