### ISSUE TITLE
iframe height should automatically adjust to contents

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/www#4]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.

## Description

> Description of the issue.

Currently, when running benchmarks and tests, we use a fixed sized `iframe`. When viewing results, not always obvious that more contents exist unless one happens to intentionally or inadvertently scroll the `iframe`. Ideally, from a visual perspective, the user need not know whether we're embedding an `iframe` or not, and we'd automatically adjust the `iframe` height based on the content height.

For some inspiration, see <https://stackoverflow.com/questions/9975810/make-iframe-automatically-adjust-height-according-to-the-contents-without-using>

## Related Issues

> Does this issue have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

#### Demo

> If relevant, provide a link to a live demo.

For a live demo of the issue, see

-   API docs and run either package tests or benchmarks

#### Reproduction

> What steps are required to reproduce the unexpected output?

In order to reproduce this bug, do the following:

-   see the API docs and run either tests or benchmarks

#### Expected Results

> What are the expected results?

The following results are expected:

-   We would not see an `iframe` scrollbar.

#### Actual Results

> What are the actual results?

The following are the actual results:

-   If results exceed the `iframe` height, we have to scroll to see the hidden results.

#### Environments

> What environments are affected (e.g., `Node v0.4.x`, `Chrome`, `IE 11`)? If Node.js, include the `npm` version, operating system, and any other potentially relevant platform information.

The following environments are affected:

-   Chrome

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by Planeshifter** [comment]
This issue is now resolved.
