### ISSUE TITLE
[Bug]: printing should always be done in "light" mode

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/www#49]
Currently, if a user tries to print package documentation, the rendered docs use the current theme. Hence, if in dark mode, the print document will also be in dark mode. This is likely not desired (e.g., imagine printing 10 pages with black backgrounds).

Presumably, the fix here is to always switch the application to "light" mode, generate the print docs, and then revert to theme back to its original value before printing.

**Comment by Planeshifter** [comment]
Hmm, that shouldn't be the case, see https://github.com/stdlib-js/www/blob/c3d227a0eb8a0f2db66a429c61cb40e9d324a7e6/src/components/readme/print_button.jsx#L85

For me, printing via the button does indeed switch to light mode and then back?

**Comment by Planeshifter** [comment]
This should also already work when directly invoking the print dialog window (e.g., via `Ctrl + P` on Chrome).

**Comment by kgryte** [comment]
I did this on mobile, so maybe it only happens there?

**Comment by kgryte** [comment]
![IMG_3235](https://user-images.githubusercontent.com/2643044/169625530-ea85ea51-d2d7-4be6-b0d6-d69c4c993f11.PNG)

**Comment by Planeshifter** [comment]
Cannot reproduce myself: Has worked on all my browsers on laptop, Android phone, and on an iPad on Safari / Chrome.

Judging from above screenshot, formatting is also off with no left margin.

**Comment by kgryte** [comment]
Not able to reproduce on MacOS Safari.

**Comment by Planeshifter** [comment]
Is this an older iPhone? Per MDN, `onbeforeprint` has been supported in Safari since `v13` (see: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeprint_event).

**Comment by kgryte** [comment]
It is an older iPhone. Not sure what Safari version it's running though.

**Comment by kgryte** [comment]
Ah...seems as though the Safari version should match the iOS version. I am on iOS 12.5.5, so don't have `beforeprint` support, it seems.

**Comment by kgryte** [comment]
Given that users are unlikely to want to print on mobile devices, especially older iOS devices, I'll close this out.

**Comment by Planeshifter** [comment]
Yeah, Apple doesn't provide updates for their browsers on older devices. Starting with version 13, things work:
![print_color](https://user-images.githubusercontent.com/1913638/169626035-fbcf0000-9c33-424d-bfe3-343d6be88586.gif)

**Comment by kgryte** [comment]
Thanks for checking!

**Comment by kgryte** [comment]
I also noticed various other rendering issues when viewing the stdlib docs on my phone, and I'm wondering if some of them are just due to it being an older Safari version.
