### ISSUE TITLE
[Bug]: Feedback checkboxes don't render correctly on Safari

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/www#52]
This is likely due to needing vendor prefixes for the `appearance` CSS rule. See <https://developer.mozilla.org/en-US/docs/Web/CSS/appearance>.

![Screen Shot 2022-05-20 at 5 16 21 PM](https://user-images.githubusercontent.com/2643044/169626605-8c90ed37-f205-46b7-b91c-644945765852.png)

**Comment by kgryte** [comment]
This has now been resolved on Safari by adding browser prefixes.

![Screen Shot 2022-05-20 at 5 43 57 PM](https://user-images.githubusercontent.com/2643044/169627825-ba638aff-007b-4737-8a03-9903e596a0da.png)

**Comment by Planeshifter** [comment]
Awesome!
