### ISSUE TITLE
Text Overflow Issue in Settings: Last Checkbox text overflow in table

### ISSUE THREAD

**Issue by nilaygit-10721** [stdlib-js/www#70]
### Description

Encountered an error when ![Image](https://github.com/user-attachments/assets/59c6bac2-520e-40df-a762-217b4fb31661)

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Reproduction

```shell
- a
- b
- c
```

### Expected Results

```shell

```

### Actual Results

```shell

```

### Environments

Microsoft Edge

### Checklist

- [x] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.

**Comment by nilaygit-10721** [comment]
i am working on it

**Comment by nilaygit-10721** [comment]
@kgryte, could you please provide links for setting up this code on a local machine?

**Comment by kgryte** [comment]
@nilaygit-10721 You may have luck from the discussion on a separate issue: https://github.com/stdlib-js/www/issues/64

**Comment by headlessNode** [comment]
@nilaygit-10721 do you have anything in progress?
